name: Testing

on:
  push:
    branches:
      - main

env:
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY}}
  POSTGRES_URL: ${{ secrets.POSTGRES_URL}}
  POSTGRES_PRISMA_URL: ${{ secrets.POSTGRES_PRISMA_URL}}
  POSTGRES_URL_NO_SSL: ${{ secrets.POSTGRES_URL_NO_SSL}}
  POSTGRES_URL_NON_POOLING: ${{ secrets.POSTGRES_URL_NON_POOLING}}
  POSTGRES_USER: ${{ secrets.POSTGRES_USER}}
  POSTGRES_HOST: ${{ secrets.POSTGRES_HOST}}
  POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD}}
  POSTGRES_DATABASE: ${{ secrets.POSTGRES_DATABASE}}
  NEXT_PUBLIC_SITE_URL: ${{ secrets.NEXT_PUBLIC_SITE_URL}}

jobs:
  cron:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ["20.x"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up NodeJS ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      - name: Build the app
        run: npm run build
      - name: Run the app
        run: echo "Hello, world!"