name: Verify Builds

on:
  push:
    branches:
      - main

env:
    AUTH_SECRET: ${{ secrets.AUTH_SECRET }}
    AUTH_GITHUB_ID: ${{ secrets.AUTH_GITHUB_ID }}
    AUTH_GITHUB_SECRET: ${{ secrets.AUTH_GITHUB_SECRET }}
    AUTH_RESEND_KEY: ${{ secrets.AUTH_RESEND_KEY }}
    OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
    POSTGRES_PRISMA_URL: ${{ secrets.POSTGRES_PRISMA_URL }}
    NEXT_PUBLIC_SITE_URL: ${{ secrets.NEXT_PUBLIC_SITE_URL }}
    VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
    VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

jobs:
  build-project:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
      - name: Install dependencies
        run: npm ci
      - name: Build the app
        run: npm run build

  deploy-migration:
    needs: [build-project]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
      - name: Install dependencies
        run: npm ci
      - name: Apply all pending migrations to the database
        run: npx prisma migrate deploy

  deploy-production:
    needs: [deploy-migration]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}